"""update

Revision ID: 7d7fd408350c
Revises: 
Create Date: 2019-04-07 13:36:59.533781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7fd408350c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'team_size',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['id', 'platform_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('matches', 'team_size',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
